version: '3'

services:
  dbase:
    image: postgres:alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    networks:
      database_net:
        aliases:
          - database
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    build: ./api
    container_name: rest_api
    ports:
      - "7000:7000"
    depends_on:
      - dbase
    command: sh -c "/wait && /app/run_api.sh"
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      api_net:
        aliases:
          - api
      database_new:
        aliases:
          - database

networks:
  database_net:
  api_net:

volumes:
  db:
    driver: local
